### ISSUE TITLE
I tried to translate the file to Korean, but it is still being translated to Spanish.

### ISSUE THREAD

**Issue by khj20000925** [KryptoST/SRTranslatorGUI-Python#1]
Hi, I recently tried to translate subtitles created with WHISPER AI into my native language.
However, despite specifying des lang as Korean, the result I actually get is Spanish.

![image](https://github.com/KryptoST/SRTranslatorGUI-Python/assets/124992748/841b0130-88a3-462c-90c1-63fcb29dd266)
![image](https://github.com/KryptoST/SRTranslatorGUI-Python/assets/124992748/b816cad5-6356-435e-9392-f724e99d6dc8)
![image](https://github.com/KryptoST/SRTranslatorGUI-Python/assets/124992748/8ac87b8b-1d8b-45a7-aed5-2f71dca23b38)

How to fix it?
The same thing happens when the source lang is English.

**Comment by KryptoST** [comment]
what version are you using?

**Comment by khj20000925** [comment]
https://github.com/sinedie/SRTranslator/releases/tag/v0.2.7

This one, mate.

Thank you for responding.

Have a good day.

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by KryptoST** [comment]
I had already reported that error but I only solved it in the beta version and the other one did not solve it.

**Comment by KryptoST** [comment]
use version 2.0.3b, probably patch the other version tomorrow

**Comment by khj20000925** [comment]
Then where Can I find it?

I did not found beta version on here.

https://github.com/sinedie/SRTranslator/releases


Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by khj20000925** [comment]
Thank you! I will try this.

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________

**Comment by KryptoST** [comment]
https://github.com/KryptoST/SRTranslatorGUI/releases/tag/v2.0.3b

**Comment by KryptoST** [comment]
Hello, I already solved the error in the other version.

https://github.com/KryptoST/SRTranslatorGUI/releases/tag/v1.1.2

note: version 1 is the version that python uses and version 2 is not.
